# Week 6: Final Real-World Project
# Breast Cancer Diagnosis Prediction System

This project uses the Breast Cancer Wisconsin Dataset
to predict whether a breast tumor is benign or malignant.

In [104]:
import pandas as pd
import joblib

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

In [105]:
cancer = load_breast_cancer()

X = cancer.data
y = cancer.target

print("Dataset loaded successfully!")
print("Features:", X.shape)
print("Target:", y.shape)

Dataset loaded successfully!
Features: (569, 30)
Target: (569,)


In [106]:
df = pd.DataFrame(
    cancer.data,
    columns=cancer.feature_names
)

df["Diagnosis"] = cancer.target

df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,Diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0


In [107]:
print("Target Classes:")
print(cancer.target_names)

print("\nClass Distribution:")
print(df["Diagnosis"].value_counts())

Target Classes:
['malignant' 'benign']

Class Distribution:
Diagnosis
1    357
0    212
Name: count, dtype: int64


In [108]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (455, 30)
Testing data: (114, 30)


In [109]:
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

print("Random Forest model trained successfully!")

Random Forest model trained successfully!


In [110]:
y_pred = model.predict(X_test)

print("Predictions made successfully!")
print(y_pred[:20])

Predictions made successfully!
[0 1 0 0 0 1 1 0 0 0 1 0 1 0 0 1 1 1 1 1]


In [111]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy Score:", accuracy)

Accuracy Score: 0.956140350877193


In [112]:
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[39  3]
 [ 2 70]]


In [113]:
report = classification_report(
    y_test,
    y_pred,
    target_names=cancer.target_names
)

print("Classification Report:")
print(report)

Classification Report:
              precision    recall  f1-score   support

   malignant       0.95      0.93      0.94        42
      benign       0.96      0.97      0.97        72

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



In [114]:
print("BREAST CANCER DIAGNOSIS MODEL")
print("=============================")
print("Accuracy Score:", accuracy)

print("\nConfusion Matrix:")
print(cm)

print("\nClassification Report:")
print(report)

BREAST CANCER DIAGNOSIS MODEL
Accuracy Score: 0.956140350877193

Confusion Matrix:
[[39  3]
 [ 2 70]]

Classification Report:
              precision    recall  f1-score   support

   malignant       0.95      0.93      0.94        42
      benign       0.96      0.97      0.97        72

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



In [115]:
joblib.dump(model, "breast_cancer_model.joblib")

print("Model saved successfully!")

Model saved successfully!


In [116]:
import os

print(os.listdir())

['.config', 'breast_cancer_model.joblib', 'sample_data']


In [117]:
loaded_model = joblib.load("breast_cancer_model.joblib")

print("Model loaded successfully!")

Model loaded successfully!


In [118]:
sample = X_test[0].reshape(1, -1)

prediction = loaded_model.predict(sample)

print("Sample Prediction:")

if prediction[0] == 0:
    print("Diagnosis: Malignant")
else:
    print("Diagnosis: Benign")

Sample Prediction:
Diagnosis: Malignant
